### PR TITLE
New Grid Agent Config Files

### PR DESCRIPTION
**Pull request by eliasleb**
The old (full) GA config file was kept as gaconfig_full_grid_agent.json

### CODE REVIEW

**Comment by LCA2-EPFL** [comment]
thanks Elias but we don't need to keep the full ga config. what do you think?

**Comment by eliasleb** [comment]
I thought that maybe customers that bought the full grid agent would thus be able to fully configure the GA and test it in T-RECS. But I can remove it! (Or can you accept only the commit that updated the GA config?)

**Comment by LCA2-EPFL** [comment]
to such customers, we will provide the full grid agent with full config file. so, we don't care about that as of now.

**Comment by eliasleb** [comment]
All right! I'll do another commit and remove the other file.

**Pull request merged**
